apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: dd-app-availability
  labels:
    service: dd
    feature: app
    slo_name: availability
spec:
  description: 99% of app requests return a valid HTTP code
  backend: datadog
  method: query_slo
  exporters: []
  service_level_indicator:
    slo_id: ${DATADOG_SLO_ID}
