"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class WriteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIMESERIES_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    @property
    def timeseries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TimeSeries]: ...
    @property
    def metadata(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MetricMetadata]: ...
    def __init__(self,
        *,
        timeseries : typing.Optional[typing.Iterable[global___TimeSeries]] = ...,
        metadata : typing.Optional[typing.Iterable[global___MetricMetadata]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata",b"metadata","timeseries",b"timeseries"]) -> None: ...
global___WriteRequest = WriteRequest

class MetricMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class MetricType(_MetricType, metaclass=_MetricTypeEnumTypeWrapper):
        pass
    class _MetricType:
        V = typing.NewType('V', builtins.int)
    class _MetricTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MetricType.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNKNOWN = MetricMetadata.MetricType.V(0)
        COUNTER = MetricMetadata.MetricType.V(1)
        GAUGE = MetricMetadata.MetricType.V(2)
        HISTOGRAM = MetricMetadata.MetricType.V(3)
        GAUGEHISTOGRAM = MetricMetadata.MetricType.V(4)
        SUMMARY = MetricMetadata.MetricType.V(5)
        INFO = MetricMetadata.MetricType.V(6)
        STATESET = MetricMetadata.MetricType.V(7)

    UNKNOWN = MetricMetadata.MetricType.V(0)
    COUNTER = MetricMetadata.MetricType.V(1)
    GAUGE = MetricMetadata.MetricType.V(2)
    HISTOGRAM = MetricMetadata.MetricType.V(3)
    GAUGEHISTOGRAM = MetricMetadata.MetricType.V(4)
    SUMMARY = MetricMetadata.MetricType.V(5)
    INFO = MetricMetadata.MetricType.V(6)
    STATESET = MetricMetadata.MetricType.V(7)

    TYPE_FIELD_NUMBER: builtins.int
    METRIC_FAMILY_NAME_FIELD_NUMBER: builtins.int
    HELP_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    type: global___MetricMetadata.MetricType.V = ...
    """Represents the metric type, these match the set from Prometheus.
    Refer to pkg/textparse/interface.go for details.
    """

    metric_family_name: typing.Text = ...
    help: typing.Text = ...
    unit: typing.Text = ...
    def __init__(self,
        *,
        type : global___MetricMetadata.MetricType.V = ...,
        metric_family_name : typing.Text = ...,
        help : typing.Text = ...,
        unit : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["help",b"help","metric_family_name",b"metric_family_name","type",b"type","unit",b"unit"]) -> None: ...
global___MetricMetadata = MetricMetadata

class TimeSeries(google.protobuf.message.Message):
    """TimeSeries represents samples and labels for a single time series."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LABELS_FIELD_NUMBER: builtins.int
    SAMPLES_FIELD_NUMBER: builtins.int
    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Label]: ...
    @property
    def samples(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Sample]: ...
    def __init__(self,
        *,
        labels : typing.Optional[typing.Iterable[global___Label]] = ...,
        samples : typing.Optional[typing.Iterable[global___Sample]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["labels",b"labels","samples",b"samples"]) -> None: ...
global___TimeSeries = TimeSeries

class Label(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    value: typing.Text = ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        value : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","value",b"value"]) -> None: ...
global___Label = Label

class Sample(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    value: builtins.float = ...
    timestamp: builtins.int = ...
    def __init__(self,
        *,
        value : builtins.float = ...,
        timestamp : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["timestamp",b"timestamp","value",b"value"]) -> None: ...
global___Sample = Sample
