apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: gae-app-latency724ms
  labels:
    service_name: gae
    feature_name: app
    slo_name: latency724ms
spec:
  description: Latency of App Engine app requests < 724ms
  error_budget_policy: cloud_service_monitoring
  backend: cloud_service_monitoring
  method: basic
  exporters: []
  service_level_indicator:
    app_engine:
      project_id: ${GAE_PROJECT_ID}
      module_id: ${GAE_MODULE_ID}
    latency:
      threshold: 724  # ms
  goal: 0.999
