apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: gae-app-latency724ms
  labels:
    service: gae
    feature: app
    slo_name: latency724ms
spec:
  description: Latency of App Engine app requests < 724ms
  backend: cloud_service_monitoring
  method: distribution_cut
  exporters: []
  service_level_indicator:
    filter_valid: >
      project=${GAE_PROJECT_ID}
      metric.type="appengine.googleapis.com/http/server/response_latencies"
      resource.type="gae_app"
      metric.labels.response_code >= 200
      metric.labels.response_code < 500
    range_min: 0
    range_max: 724
