apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: gke-service-availability
  labels:
    service_name: gke
    feature_name: service
    slo_name: availability
spec:
  description: Availability of GKE service
  error_budget_policy: cloud_service_monitoring
  backend: cloud_service_monitoring
  method: basic
  exporters: []
  service_level_indicator:
    cluster_istio:
      project_id: ${GKE_PROJECT_ID}
      zone: ${GKE_LOCATION}
      cluster_name: ${GKE_CLUSTER_NAME}
      service_namespace: ${GKE_SERVICE_NAMESPACE}
      service_name: ${GKE_SERVICE_NAME}
    availability: {}
  goal: 0.98
