apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: gke-service-latency724ms
  labels:
    service_name: gke
    feature_name: service
    slo_name: latency724ms
spec:
  description: Latency of GKE service requests < 724ms
  error_budget_policy: cloud_service_monitoring
  backend: cloud_service_monitoring
  method: basic
  exporters: []
  service_level_indicator:
    cluster_istio:
      project_id: ${GKE_PROJECT_ID}
      location: ${GKE_LOCATION}
      cluster_name: ${GKE_CLUSTER_NAME}
      service_namespace: ${GKE_SERVICE_NAMESPACE}
      service_name: ${GKE_SERVICE_NAME}
    latency:
      threshold: 724         # ms
  goal: 0.999
