apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: custom-test-availability-ratio
  labels:
    service: custom
    feature: test
    slo_name: availability-ratio
spec:
  description: 99.99% of fake requests to custom backends are valid
  backend: custom.custom_backend.CustomBackend
  method: good_bad_ratio
  exporters:
  - custom.custom_exporter.CustomMetricExporter
  service_level_indicator: {}
  goal: 0.999
