apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
    name: splunk-app-availability
    labels:
        service_name: splunk
        feature_name: app
        slo_name: availability
spec:
    description: 99% of app requests return a valid HTTP code
    backend: splunk
    method: query_sli
    exporters: []
    service_level_indicator:
        search_query: search index=access_logs host=web* status!=200 status!=403 | stats count(status="200") as good count(status!="403") as valid | eval sli=round(good/valid,3)
    goal: 0.99
