apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: lb-request-availability
  labels:
    service_name: lb
    feature_name: request
    slo_name: availability
spec:
  description: Availability of HTTP Load Balancer
  backend: cloud_monitoring
  method: good_bad_ratio
  exporters:
  - cloud_monitoring
  service_level_indicator:
    filter_good: >
      project=${LB_PROJECT_ID}
      metric.type="loadbalancing.googleapis.com/https/request_count"
      resource.type="https_lb_rule"
      ( metric.label.response_code_class="200" OR
        metric.label.response_code_class="300" OR
        metric.label.response_code_class="400" )
    filter_valid: >
      project=${LB_PROJECT_ID}
      metric.type="loadbalancing.googleapis.com/https/request_count"
      resource.type="https_lb_rule"
  goal: 0.98
