apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: lb-request-latency724ms
  labels:
    service_name: lb
    feature_name: request
    slo_name: latency724ms
spec:
  description: Latency of HTTP Load Balancer < 724ms
  backend: cloud_monitoring
  method: distribution_cut
  exporters:
  - cloud_monitoring
  service_level_indicator:
    filter_valid: >
      project=${LB_PROJECT_ID}
      metric.type="loadbalancing.googleapis.com/https/total_latencies"
      resource.type="https_lb_rule"
      ( metric.label.response_code_class="200" OR
        metric.label.response_code_class="300" OR
        metric.label.response_code_class="400" )
    good_below_threshold: true
    threshold_bucket: 19
  goal: 0.98
