apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: dt-app-latency
  labels:
    service_name: dt
    feature_name: app
    slo_name: latency
spec:
  description: 99.9% of app 2xx requests return within 50ms
  backend: dynatrace
  method: threshold
  exporters:
  - dynatrace
  service_level_indicator:
    query_valid:
      metric_selector: ext:app.request_latency:filter(and(eq(app,test_app),eq(env,prod),eq(status_code_class,2xx)))
      entity_selector: type(HOST)
    threshold: 50000          # us
  goal: 0.999
