name: Build and push a Docker image to Google Cloud Platform (GCP) Registry

on:
  push:
    branches:
      - master
      - deploy-*
    tags:
      - v*.*.*

jobs:
  cloudbuild:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Check release version
        id: check-tag
        run: |
          echo "version=$(echo ${{ github.event.ref }} | cut -d / -f 3 | cut -c2-)" >> $GITHUB_OUTPUT
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate to GCP
        id: authenticate
        uses: google-github-actions/auth@v1
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker container and publish on GCR
        run: make cloudbuild || true
        env:
          GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
          CLOUDBUILD_PROJECT_ID: ${{ secrets.CLOUDBUILD_PROJECT_ID }}
          VERSION: ${{ steps.check-tag.outputs.match == 'true' && steps.check-tag.outputs.version ||  github.event.pull_request.head.sha || github.sha }}

      - name: Build Docker container and publish on GCR [latest]
        run: make cloudbuild || true
        if: ${{ steps.check-tag.outputs.match == 'true' }}
        env:
          GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
          CLOUDBUILD_PROJECT_ID: ${{ secrets.CLOUDBUILD_PROJECT_ID }}
          VERSION: latest
