name: make-master
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install deps
        run: >
          sudo apt-get install gcc libpq-dev -y &&
          sudo apt-get install python-dev python-pip -y &&
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y &&
          pip3 install -U wheel setuptools

      - name: Run all
        run: make all
