name: rc-release-version
on:
  push:
    branches:
      - release-v*.*.*-rc*
jobs:
  release-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Verify version is a release candidate"
        run: |
          cat "setup.py" | grep "version = .*-rc*"
      - uses: actions/setup-python@master
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Run all tests
        run: make
        env:
          MIN_VALID_EVENTS: "10"
          GOOGLE_APPLICATION_CREDENTIALS: tests/unit/fixtures/fake_credentials.json

      - name: Release PyPI package
        run: make deploy
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
  release-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Build Docker container and publish on GCR
        run: make cloudbuild
        env:
          GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
          CLOUDBUILD_PROJECT_ID: ${{ secrets.CLOUDBUILD_PROJECT_ID }}
